### ISSUE TITLE
php-cs-fixer issue on php <= 7.1

### ISSUE THREAD

**Issue by mykiwi** [mykiwi/dockerfiles#12]
```
$ docker run --rm -ti mykiwi/phaudit:7.1 php-cs-fixer -v  
Unable to find image 'mykiwi/phaudit:7.1' locally
...
Digest: sha256:22bca92d361dc77f323044d12f9c155d5a978fe396469f28df0459cf0439e9c5
...

Fatal error: Declaration of Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch(Symfony\Contracts\EventDispatcher\object $event, ?string $eventName = NULL): Symfony\Contracts\EventDispatcher\object must be compatible with Psr\EventDispatcher\EventDispatcherInterface::dispatch(Psr\EventDispatcher\object $event) in /usr/local/src/vendor-bin/symfony-friendly/vendor/symfony/event-dispatcher-contracts/EventDispatcherInterface.php on line 19
```

**Comment by NotQuentin** [comment]
Salut,

En regardant le Dockerfile: `FROM composer as src`, `composer` contient la version 7.4.1 de PHP.  Il doit build les librairies en conséquence.  Sur le dockerhub de composer, la dernière version qui semble utiliser PHP 7.1 à l'air d'être la 1.5.1.

En tout cas, merci pour tes images docker car elles nous rendent bien service pour notre CI.

**Comment by mykiwi** [comment]
Merci @NotQuentin pour ces infos :)

**Comment by mykiwi** [comment]
Le problème était que `FROM composer` utilisait PHP 7.3.12 plutôt que la version attendu...
