### ISSUE TITLE
[PHAUDIT] - Remove PHP Dead Code Detector 

### ISSUE THREAD

**Issue by beleneglorion** [mykiwi/dockerfiles#3]
Hi 
the phaudit is a nice docker image with cool tools but

First :  PHP Dead Code Detector  is not compatible with PHP 7.X code, when trying to parse PHP code with COALESLE operator,  phpdcd crash.

Second: PHPDCD is not active anymore and no one has forked the project to maintain it.

why keep this tools ?

**Comment by mykiwi** [comment]
Hi

Thanks.

You are right.
But it still usable if you exclude files that use `??`, like this for example:
```shell
phpdcd --names-exclude=$(grep -r "??" . | awk -F: '{gsub("\.\/","",$1); print $1}' | paste -sd "," -) .
```

I'm not sure that I want to remove it if we don't have an alternative.
